-- MySQL Script generated by MySQL Workbench
-- Thu Jun 25 11:43:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbPrueba
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbPrueba` ;

-- -----------------------------------------------------
-- Schema dbPrueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPrueba` DEFAULT CHARACTER SET utf8 ;
USE `dbPrueba` ;

-- -----------------------------------------------------
-- Table `dbPrueba`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPrueba`.`request` ;

CREATE TABLE IF NOT EXISTS `dbPrueba`.`request` (
  `req_id` INT(11) NOT NULL AUTO_INCREMENT,
  `req_company` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_commercial_area` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_title` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_description` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_responsable` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_order_priority` INT(11) NOT NULL,
  `req_date` DATE NOT NULL,
  `req_init_date` DATE NULL DEFAULT '9999-12-31 00:00:00',
  `req_final_date` DATE NULL DEFAULT '9999-12-31 00:00:00',
  `req_real_final_date` DATE NULL,
  `req_status` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_advance_ptge` FLOAT NULL,
  `req_deviations_ptge` FLOAT NULL,
  `req_client_completed_deliverables` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `req_client_pending_activities` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `req_client_comments` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `req_intelix_completed_deliverables` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `req_intelix_pending_activities` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `req_intelix_comments` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `req_last_update_date` DATE NULL,
  `req_type` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_technical_area` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `req_comitee` INT(11) NULL,
  `req_comitee_points_discuss` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  PRIMARY KEY (`req_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `dbPrueba`.`collaborator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPrueba`.`collaborator` ;

CREATE TABLE IF NOT EXISTS `dbPrueba`.`collaborator` (
  `col_id` INT(11) NOT NULL AUTO_INCREMENT,
  `col_request_id` INT(11) NOT NULL,
  `col_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `col_email` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`col_id`),
  INDEX `col_request_id` (`col_request_id` ASC),
  CONSTRAINT `col_request_id`
    FOREIGN KEY (`col_request_id`)
    REFERENCES `dbPrueba`.`request` (`req_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
